In [2]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.preprocessing import StandardScaler

In [3]:
# Example dataset (you can modify)
data = {
    "Math": [80, 60, 75, 90, 50],
    "Science": [70, 85, 65, 95, 55],
    "English": [90, 75, 70, 85, 60]
}

df = pd.DataFrame(data)
print("Dataset:\n", df)

Dataset:
    Math  Science  English
0    80       70       90
1    60       85       75
2    75       65       70
3    90       95       85
4    50       55       60


🔹 Part A: Vector & Matrix Fundamentals

1️⃣ Represent vectors

In [4]:
A = df.iloc[0].values  # Student 1
B = df.iloc[1].values  # Student 2

print("Vector A:", A)
print("Vector B:", B)

Vector A: [80 70 90]
Vector B: [60 85 75]


2️⃣ Norm

In [5]:
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)

print("Norm A:", norm_A)
print("Norm B:", norm_B)

Norm A: 139.2838827718412
Norm B: 128.2575533838066


3️⃣ Dot Product

In [6]:
dot_product = np.dot(A, B)
print("Dot Product:", dot_product)

Dot Product: 17500


4️⃣ Angle Between Vectors

In [7]:
angle = np.arccos(dot_product / (norm_A * norm_B))
angle_deg = np.degrees(angle)

print("Angle (degrees):", angle_deg)

Angle (degrees): 11.589436007804773


5️⃣ Cross Product (3D)

In [8]:
cross_product = np.cross(A, B)
print("Cross Product:", cross_product)

Cross Product: [-2400  -600  2600]


6️⃣ Projection of A onto B

In [9]:
projection = (np.dot(A, B) / np.dot(B, B)) * B
print("Projection of A onto B:", projection)

Projection of A onto B: [63.82978723 90.42553191 79.78723404]


🔹 Part B: Matrix Operations

7️⃣ Matrix Formation

In [10]:
M = df.values
print("Matrix M:\n", M)

Matrix M:
 [[80 70 90]
 [60 85 75]
 [75 65 70]
 [90 95 85]
 [50 55 60]]


8️⃣ Matrix Addition

In [11]:
print("M + M:\n", M + M)

M + M:
 [[160 140 180]
 [120 170 150]
 [150 130 140]
 [180 190 170]
 [100 110 120]]


9️⃣ Matrix Multiplication

In [12]:
print("M x M^T:\n", np.dot(M, M.T))

M x M^T:
 [[19400 17500 16850 21500 13250]
 [17500 16450 15275 19850 12175]
 [16850 15275 14750 18875 11525]
 [21500 19850 18875 24350 14825]
 [13250 12175 11525 14825  9125]]


🔟 Transpose

In [13]:
print("Transpose:\n", M.T)

Transpose:
 [[80 60 75 90 50]
 [70 85 65 95 55]
 [90 75 70 85 60]]


1️⃣1️⃣ Determinant (square matrix required)

In [14]:
square_matrix = np.dot(M, M.T)
det = np.linalg.det(square_matrix)

print("Determinant:", det)

Determinant: 0.0


🔹 Part C: Linear Transformations

1️⃣2️⃣ Simple Transformation (Scaling)

In [15]:
scaled = 2 * M
print("Scaled Matrix:\n", scaled)

Scaled Matrix:
 [[160 140 180]
 [120 170 150]
 [150 130 140]
 [180 190 170]
 [100 110 120]]


1️⃣3️⃣ Rotation (2D Example using first 2 columns)

In [16]:
theta = np.radians(45)

rotation_matrix = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

rotated = np.dot(df[["Math", "Science"]], rotation_matrix)
print("Rotated Data:\n", rotated)

Rotated Data:
 [[106.06601718  -7.07106781]
 [102.53048327  17.67766953]
 [ 98.99494937  -7.07106781]
 [130.81475452   3.53553391]
 [ 74.24621202   3.53553391]]


🔹 Part D: Eigenvalues & Decomposition

1️⃣4️⃣ Covariance Matrix

In [17]:
cov_matrix = np.cov(M.T)
print("Covariance Matrix:\n", cov_matrix)

Covariance Matrix:
 [[255.   151.25 155.  ]
 [151.25 255.   120.  ]
 [155.   120.   142.5 ]]


1️⃣5️⃣ Eigenvalues & Eigenvectors

In [18]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [509.66111931 110.17150833  32.66737236]
Eigenvectors:
 [[-0.64429345 -0.5602364  -0.52059689]
 [-0.60382402  0.79039786 -0.1032849 ]
 [-0.46934263 -0.24780312  0.84753236]]


1️⃣6️⃣ LU Decomposition

In [19]:
from scipy.linalg import lu

P, L, U = lu(square_matrix)

print("L:\n", L)
print("U:\n", U)

L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.90232558  1.          0.          0.          0.        ]
 [ 0.81395349 -0.71266968  1.          0.          0.        ]
 [ 0.61627907  0.14140271  0.375       1.          0.        ]
 [ 0.78372093  0.68552036 -0.375       0.          1.        ]]
U:
 [[ 2.15000000e+04  1.98500000e+04  1.88750000e+04  2.43500000e+04
   1.48250000e+04]
 [ 0.00000000e+00 -4.11162791e+02 -1.81395349e+02 -4.71627907e+02
  -1.26976744e+02]
 [ 0.00000000e+00  0.00000000e+00 -2.17647059e+02 -3.05882353e+02
   1.76470588e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.81898940e-12
   1.81898940e-12]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]]


1️⃣7️⃣ SVD

In [20]:
U, S, Vt = np.linalg.svd(M)

print("U:\n", U)
print("Singular Values:\n", S)
print("Vt:\n", Vt)

U:
 [[-0.47991907 -0.55598701  0.48537851  0.24754908 -0.40457791]
 [-0.44062505  0.71919942  0.3246561  -0.32695129 -0.27623003]
 [-0.41917556 -0.37494593 -0.36713974 -0.73022772  0.12523293]
 [-0.53921832  0.1789167  -0.6302015   0.52775678 -0.03938614]
 [-0.33024642  0.03217144  0.35645561  0.14164239  0.86184635]]
Singular Values:
 [288.89224351  20.99256212  13.25081034]
Vt:
 [[-0.55837832 -0.580435   -0.59271313]
 [-0.55909641  0.79113209 -0.24803473]
 [-0.61288242 -0.19288657  0.76627013]]


🔹 Part E: Dimensionality Reduction

1️⃣8️⃣ PCA

In [21]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(M)

pca = PCA(n_components=2)
pca_result = pca.fit_transform(scaled_data)

print("PCA Result:\n", pca_result)

PCA Result:
 [[ 1.01182112e+00 -9.30350124e-01]
 [-9.98266084e-02  1.01328044e+00]
 [-5.09785518e-01 -4.71868736e-01]
 [ 2.08314090e+00  3.87129263e-01]
 [-2.48534990e+00  1.80916003e-03]]


1️⃣9️⃣ LDA (Classification)

In [22]:
# Create labels (Above Avg = 1, Below Avg = 0)
df["Average"] = df.mean(axis=1)
df["Label"] = (df["Average"] > df["Average"].mean()).astype(int)

X = df[["Math", "Science", "English"]]
y = df["Label"]

lda = LDA(n_components=1)
lda_result = lda.fit_transform(X, y)

print("LDA Result:\n", lda_result)

LDA Result:
 [[ 2.34961564]
 [-0.80097035]
 [-0.4729246 ]
 [ 1.54441244]
 [-2.62013313]]
